### ISSUE TITLE
Gemini API Duplicated Translations

### ISSUE THREAD

**Issue by voidpenguin-28** [voidpenguin-28/Textractor-ExtraExtensions#4]
> Sir @voidpenguin-28 I'm using Gemini and it's working thanks to your instructions however, the translation is duplicating
> 
> ![image](https://private-user-images.githubusercontent.com/171616207/373179904-e7d053fb-4da5-424f-ba55-c5aae66eebdd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc5NTg4MDgsIm5iZiI6MTcyNzk1ODUwOCwicGF0aCI6Ii8xNzE2MTYyMDcvMzczMTc5OTA0LWU3ZDA1M2ZiLTRkYTUtNDI0Zi1iYTU1LWM1YWFlNjZlZWJkZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwM1QxMjI4MjhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03MzQ1NmI5YTlhZTcwZDRkOTljMTVjOWExNjE2ZTAyMWVlNDhmNzZiYmM0YTRkOTgwYTg0ODRiNTY0ZTkyMGViJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.MdcewdsaH-YMIijNlu8Z-Fof6cJFlciDI-sI9_JGZIg)
> 
> How do I fix this?

Issue reported by @hotdogman1234 in the Textractor GPT thread.

**Comment by voidpenguin-28** [comment]
@hotdogman1234

Can you provide the following information:
1. What model are you using?
2. Can you enable DebugMode for the extension and submit your "gpt-request-log.txt" once the issue has occurred at least one time while this mode is on?

My initial theory is that it might be Gemini itself being the problem here (the API returning the translation twice).

**Comment by hotdogman1234** [comment]
Hi Sir Penguin, 

I'm using gemini 1.5 flash just like you recommended

As for the debug mode, I don't know how to do that. 

The double translation is only appearing on the main app, in the screenshot I provided, but in a separate window, it's only showing the translation once

**Comment by voidpenguin-28** [comment]
DebugMode can be enabled by opening Textractor.ini in a text editor. Then
in the settings for the extension, set DebugMode=1.

This will make all API request data log to gpt-request-log.txt.

This will help me narrow down the root cause.

**Comment by hotdogman1234** [comment]
[gpt-request-log.txt](https://github.com/user-attachments/files/17247475/gpt-request-log.txt)

Hi again sir voidpenguin-28

The incident appeared again. I uploaded the log as you've requested

Thanks!

**Comment by voidpenguin-28** [comment]
Thank you.  I have a few more questions.

1. Can you let me know which line of text repeated twice (of the lines that were logged)?
2. Are you using the latest version of the GptApiTranslate extension?
3. Would you be able to provide a screenshot of your current Textractor extension list?

**Comment by hotdogman1234** [comment]
1) Any of the lines repeat after the initial translation. Its very first translation will produce a normal result, the subsequent texts are doubled

2) Yes, I'm using the latest model

3) Sure. 
![image](https://github.com/user-attachments/assets/bf19ca76-64c3-4822-b35f-d4ed9fede8d6)

**Comment by hotdogman1234** [comment]
I don't know where to find the remove repeated phrases 2 extension, I would like to add it as well

**Comment by voidpenguin-28** [comment]
Ah, it's likely your extension list causing these problems.  A few problems there:


1. You are using 2 different translation extensions, GptApiTranslate and Google Translate. You should only have one translation extension.  If you are using the GptApiTranslate extension, then you should remove the Google Translate extension.
2. The translation cache extensions are in the wrong order. "TranslationCache.Read" should be **before** GptApiTranslate.

Therefore, you should update your extension list to the following:
*Remove Repeated Characters
Regex Filter
Copy to Clipboard
Textractor.VndbCharNameMapper
Textractor.TranslationCache.Read
Textractor.GptApiTranslate
Textractor.TranslationCache.Write
Extra Window
Extra Newlines*


As for "Remove Repeated Phrases 2", that extension should be in the root directory of Textractor:
![image](https://github.com/user-attachments/assets/2f782f8e-766a-4af9-8c9d-6fadcc1216ab)

**Comment by hotdogman1234** [comment]
I have updated the extensions order but now the english translation has disappeared

![image](https://github.com/user-attachments/assets/b0e19cc8-68f6-4884-b151-32d6c5897e3d)
![image](https://github.com/user-attachments/assets/0257c42d-c38a-467c-9992-d1aa9ecd4353)
[gpt-request-log.txt](https://github.com/user-attachments/files/17247859/gpt-request-log.txt)

**Comment by voidpenguin-28** [comment]
Here are two things to try out.

1. The extension order issues may have resulted in the translation cache being messed up. Try deleting the cache file "Textractor.TranslationCache.txt" (you may need to close Textractor first), then try testing again.
![image](https://github.com/user-attachments/assets/d3122d13-772e-42a2-824b-a07aa1ebcccf)
2. If the 1st step doesn't work, trying removing the "Textractor.TranslationCache.Read" and "Textractor.TranslationCache.Write" extensions and then try testing again.

**Comment by hotdogman1234** [comment]
Thanks sir. It's working again now. I need to learn how to use the Name Mapper next because the translated names are wrong haha. Thanks a lot for all your help. I appreciate it. You're awesome!

**Comment by voidpenguin-28** [comment]
Glad to help :)

As for the name mapping extension, you have to assign the VnId (from vndb) of the associated visual novel.
For example, if you are reading "Clannad", the vndb link for Clannad is:
https://vndb.org/v4

The 'v4' part of the url is the VnId of the visual novel.

Therefore, you would open up the Textractor.ini file, go to the [Textractor.VndbCharNameMapper] section, and under the 'VnIds' config value you would assign "VnIds=v4". Then the character names for Clannad would be mapped automatically.

**Comment by hotdogman1234** [comment]
AMAZING!!!! I was reading your tutorial on it but I got confused. Now I know it's that simple!
