### ISSUE TITLE
Config for LMStudio

### ISSUE THREAD

**Issue by hotdogman1234** [voidpenguin-28/Textractor-ExtraExtensions#5]
Hi Sir void,

I'm still using your GPT extension on Textractor but I would like to test it using LMstudio, I edited the config by adding the local server in the url section and deleting the API key but it's not working. Do you have any tips or latest config for using this method?

Thank you

**Comment by voidpenguin-28** [comment]
Hello,

A few questions.

1: What LLM & model are you testing with?
2: Have you confirmed that the local server is running successfully on localhost and have you been able to do any successful api requests (outside of Textractor)?
3: I haven't used LM studio too much before. Is this the setup you are trying to run?
   * https://lmstudio.ai/docs/api/server
   * https://lmstudio.ai/docs/api/openai-api

**Comment by hotdogman1234** [comment]
Hi Sir 

I'm using Aya on LMstudio. 

Yes, the local server is running and working on Luna Translator. I just added the host IP in their settings and added a prompt.

I tried using it using the gpt config but it didn't work on Textractor. No, I'm not using any other setup besides yours because I don't understand them. Sorry.

Do you have any guides like with Gemini? I'm guessing using an LLM has a different config

**Comment by voidpenguin-28** [comment]
Thank you.

A few more questions and I should be able to help get the correct config set up.

1: What Url & Model are you assigning in the extension's config?
2: Can you set *DebugMode=1* in the extension's config? Then try testing out the extension with a few sentences. This will create a log file called *gpt-request-log.txt* in the Textractor's directory. Can you then post that log file here?

**Comment by hotdogman1234** [comment]
Model and URL

aya-expanse-8b
http://127.0.0.1:1234

They are from LMstudio when starting the server and loading the model, sir.

Here's a screenshot from the log inside LM studio
![image](https://github.com/user-attachments/assets/1e90cefb-187b-45cf-aee3-e9d568c332a2)

here's the txt log file from Textractor
[gpt-request-log.txt](https://github.com/user-attachments/files/18229850/gpt-request-log.txt)

**Comment by voidpenguin-28** [comment]
Try setting the following url:
http://localhost:1234/api/v0/chat/completions

**Comment by voidpenguin-28** [comment]
Or maybe this one:
http://localhost:1234/api/v1/chat/completions

**Comment by hotdogman1234** [comment]
Still not working sir

LM studio log
2024-12-23 21:42:37 [ERROR] Unexpected endpoint or method. (POST /api/v1/chat/completions). Returning 200 anyway

**Comment by voidpenguin-28** [comment]
Would you be able to share your full extension config here? Make sure to remove any sensitive info like API keys of course.

**Comment by hotdogman1234** [comment]
This is your GPT config sir, all I did was change the url and model and remove the key

[GptApi-Translate]
Disabled=0
Url=http://localhost:1234/api/v1/chat/completions
ApiKey=
Model=aya-expanse-8b
TimeoutSecs=10
NumRetries=2
SysMsgPrefix=Translate novel script to natural fluent EN. Preserve numbering. Use all JP input lines as context (previous lines). However, only return the translation for the line that starts with '99:'.
UserMsgPrefix=
NameMappingMode=0
ActiveThreadOnly=1
SkipConsoleAndClipboard=1
UseHistoryForNonActiveThreads=0
MsgHistoryCount=3
HistorySoftCharLimit=250
MsgCharLimit=300
SkipAsciiText=1
SkipIfZeroWidthSpace=1
ShowErrMsg=1
CustomRequestTemplate=
CustomResponseMsgRegex=
CustomErrorMsgRegex=
CustomHttpHeaders=
ThreadKeyFilterMode=0
ThreadKeyFilterList=
ThreadKeyFilterListDelim=|
DebugMode=1

**Comment by voidpenguin-28** [comment]
Try setting the following values and let's see if that works out. Keep the url as *http://localhost:1234/api/v1/chat/completions*

ApiKey=asdf1234
CustomHttpHeaders=Content-Type: application/json

**Comment by hotdogman1234** [comment]
Same error sir @voidpenguin-28

**Comment by voidpenguin-28** [comment]
Ok, I'll take some time to test this myself with LM studio.

**Comment by hotdogman1234** [comment]
No problem sir! Thanks for trying to help. Will wait for your update

**Comment by voidpenguin-28** [comment]
Interestingly, it works perfectly fine for me.

Are you using Textractor on the same pc as the LM studio server?
Also are you using the latest version of the extension?

**Comment by voidpenguin-28** [comment]
Oh wait, the url I gave you is inaccurate.

Try this one:
http://localhost:1234/v1/chat/completions


Also, if the model is not properly obeying your instructions, try setting the *SysMsgPrefix* as the *UserMsgPrefix*.
Ex:
SysMsgPrefix=Translate novel script to natural fluent EN. Preserve numbering. Use all JP input lines as context (previous lines). However, only return the translation for the line that starts with '99:'.
UserMsgPrefix=Translate novel script to natural fluent EN. Preserve numbering. Use all JP input lines as context (previous lines). However, only return the translation for the line that starts with '99:'.

**Comment by hotdogman1234** [comment]
Sir Void, it's working now. Thank you. I added the custom prompt as the usermsgprefix and replaced the URL. The only down side is that it's so slow to generate the translation, but other than that, it looks better than using google translate

**Comment by voidpenguin-28** [comment]
Great to hear. The generation speed is going to highly depend on how good your gpu is.

**Comment by hotdogman1234** [comment]
I understand. Regardless, I very grateful for helping me with this. Maybe you can add LM tutorial now in your library? 

Merry Christmas!
